server:
  port: 80
spring:
  application:
    name: SpringBootInitial
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
mybatis-plus:
  type-handlers-package: com.dust.springbootinitial.handler # 自定义type-handler
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 日志