server:
  port: 80
spring:
  application:
    name: SpringBootInitial
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver